/** Common OSM tag keys used to improve relevance for popular queries.
 * The orchestrator always also searches by name-regex, so arbitrary niches work even
 * if there is no entry here. */
export const OSM_TAG_HINTS: Record<string, string[]> = {
  // amenities
  dentist: ["amenity=dentist"],
  doctor: ["amenity=doctors"],
  clinic: ["amenity=clinic"],
  hospital: ["amenity=hospital"],
  pharmacy: ["amenity=pharmacy"],
  restaurant: ["amenity=restaurant"],
  cafe: ["amenity=cafe"],
  "coffee shop": ["amenity=cafe"],
  bar: ["amenity=bar"],
  pub: ["amenity=pub"],
  hotel: ["tourism=hotel"],
  hostel: ["tourism=hostel"],
  gym: ["leisure=fitness_centre"],
  "fitness center": ["leisure=fitness_centre"],
  spa: ["leisure=spa"],
  bank: ["amenity=bank"],
  atm: ["amenity=atm"],
  "real estate": ["office=estate_agent"],
  "real estate agency": ["office=estate_agent"],
  lawyer: ["office=lawyer"],
  "law firm": ["office=lawyer"],
  accountant: ["office=accountant"],
  insurance: ["office=insurance"],
  plumber: ["craft=plumber"],
  electrician: ["craft=electrician"],
  "car repair": ["shop=car_repair"],
  "auto repair": ["shop=car_repair"],
  "car dealership": ["shop=car"],
  "beauty salon": ["shop=beauty"],
  barber: ["shop=hairdresser"],
  hairdresser: ["shop=hairdresser"],
  school: ["amenity=school"],
  university: ["amenity=university"],
  "driving school": ["amenity=driving_school"],
  veterinary: ["amenity=veterinary"],
  "pet shop": ["shop=pet"],
  supermarket: ["shop=supermarket"],
  "shopping mall": ["shop=mall"],
  florist: ["shop=florist"],
  bakery: ["shop=bakery"],
  butcher: ["shop=butcher"],
  bookstore: ["shop=books"],
  "electronics store": ["shop=electronics"],
  "furniture store": ["shop=furniture"],
  "clothing store": ["shop=clothes"],
  "hardware store": ["shop=hardware"],
  jeweler: ["shop=jewelry"],
  "car wash": ["amenity=car_wash"],
  "gas station": ["amenity=fuel"],
  parking: ["amenity=parking"],
  coworking: ["amenity=coworking_space"],
  "marketing agency": ["office=advertising_agency"],
  "advertising agency": ["office=advertising_agency"],
  "web design": ["office=advertising_agency"],
  "web development": ["office=it"],
  "software company": ["office=it"],
  "it company": ["office=it"],
  "cleaning company": ["office=cleaning"],
  "security company": ["office=security"],
  "construction company": ["office=construction"],
  architect: ["office=architect"],
  engineer: ["office=engineer"],
  logistics: ["office=logistics"],
  manufacturer: ["industrial=manufacturer"],
  wholesaler: ["office=wholesale"],
  importer: ["office=importer"],
  "travel agency": ["office=travel_agent"],
  photographer: ["studio=photographer"],
  "wedding service": ["service=wedding"],
  "event company": ["service=event_planner"],
  translator: ["office=translator"],
  notary: ["office=notary"],
  taxi: ["amenity=taxi"],
};

export function osmTagsForNiche(niche: string): string[] {
  const n = niche.toLowerCase().trim();
  const tags: string[] = [];
  for (const [key, vals] of Object.entries(OSM_TAG_HINTS)) {
    if (n.includes(key) || key.includes(n)) tags.push(...vals);
  }
  return Array.from(new Set(tags));
}
